import './globals.css'
import { Space_Grotesk } from 'next/font/google'

const grotesk = Space_Grotesk({ subsets:['latin']})

export const metadata = {
  title: 'LoanLink | The app of the future',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={grotesk.className}>{children}</body>
    </html>
  )
}
